### ISSUE TITLE
Icons page

### ISSUE THREAD

**Issue by gampleman** [rightscale/design-kit#86]
Could the icons page be sorted alphabetically and could we get links to individual icons (or better icon/background combinations), similar how colors work?

**Comment by allancorbett** [comment]
Sorting alphabetically seems easy enough. 

We are going to add another page for multicoloured sprites (so Server Array Icons, SSH icons etc) which the user can download as an svg or png. Although, we won't be able to change their colours since that will affect their design.

Is that what you mean for better icon/background combinations?

**Comment by gampleman** [comment]
I mean that the permalink would include the state of those buttons that change the color.

<img width="561" alt="screen shot 2015-08-24 at 12 36 36" src="https://cloud.githubusercontent.com/assets/69144/9438265/cffe3960-4a5c-11e5-8d2d-e9cedfe6aedc.png">

**Comment by allancorbett** [comment]
Oh! That’s a great idea :] I’m iTiming today so I’ll look in to it/ask Sean.

**Comment by jasonmelgoza** [comment]
+1 on the permalink idea. Thanks @gampleman

**Comment by jasonmelgoza** [comment]
@allancorbett Is this issue still on your radar?
